zram: set QUEUE_FLAG_FAST in queue struct instead of zram struct
This line was introduced in commit "mm: swap: don't delay swap free for fast swap devices". Compiling without this commit results in the following error.

drivers/block/zram/zram_drv.c: In function 'create_device':
drivers/block/zram/zram_drv.c:1150:34: error: 'struct zram' has no member named 'queue'
  __set_bit(QUEUE_FLAG_FAST, &zram->queue->queue_flags);
                                  ^~
drivers/block/zram/zram_drv.c: At top level:

This is due to commit "UPSTREAM: zram: remove request_queue from struct zram", where queue was removed from the zram struct. Instead, we point it to the queue within this function, which does the same thing.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>